select * from [dbo].[customers];
select * from [dbo].[orders];
select * from [dbo].[baskets];
select * from [dbo].[products];
select * from [dbo].[country];


-- 1. What are the names of all the countries in the country table?
select country_name from country;

-- 2. What is the total number of customers in the customers table?
select count(customer_id) total_number_of_customers from customers;

-- 3. What is the average age of customers who can receive marketing emails (can_email is set to ‘yes’)?
select avg(age) average_age from customers
where can_email='yes';

-- 4. How many orders were made by customers aged 30 or older?
select count(order_id) amount from customers c
join orders o on c.customer_id=o.customer_id
where age >=30;

-- 5. What is the total revenue generated by each product category?
select category, sum(price) from baskets b
join orders o on b.order_id= o.order_id
join products p on p.product_id= b.product_id
group by category;

-- 6. What is the average price of products in the ‘food’ category?
select category, avg(price) avg_price from products
where category='food'
group by category;

-- 7. How many orders were made in each sales channel (sales_channel column) in the orders table?
select sales_channel, count(order_id) amount from orders
group by sales_channel;

-- 8.What is the date of the latest order made by a customer who can receive marketing emails
select c.customer_id, can_email,max(date_shop) latest_date from customers c
join orders o on c.customer_id=o.customer_id
where can_email='yes'
group by c.customer_id, can_email;

-- 9. What is the name of the country with the highest number of orders?
select top 1 country_name, count(order_id) amount from country c
join orders o on c.country_id=o.country_id
group by country_name
order by amount desc;

-- 10. What is the average age of customers who made orders in the ‘vitamins’ product category?
select category, avg(age) avg_age from customers c
join orders o on o.customer_id=c.customer_id
join baskets b on b.order_id=o.order_id
join products p on p.product_id=b.product_id
where category='vitamins'
group by category;
